<template>
<v-app>
    <Loading :active.sync="isLoading"
        :is-full-page="fullPage"
        :opacity="0.5"
        :transition="fade"
        background-color="#3E2723">
        <div class="loadingio-spinner-magnify-alu7sn2q8i9"><div class="ldio-5f9p1vioxma">
        <div><div><div></div><div></div></div></div>
        </div></div>
        </Loading>
  <transition name="fade">
    <v-container v-if="show" fluid class="container-fluid fill-height" id="welcomebg">
      <div class="text-center" id="enter-button">
        <v-btn to='/home'
        rounded
        large
        color="brown lighten-5"><v-icon>mdi-home-import-outline</v-icon> 進入首頁</v-btn>
      </div>
    </v-container>
  </transition>
</v-app>
</template>
<style>
@keyframes ldio-5f9p1vioxma {
  0%    { transform: translate(2px,2px) }
  33.33% { transform: translate(102px,2px) }
  66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}

.ldio-5f9p1vioxma > div {
  transform: scale(0.66);
  transform-origin: 100px 100px;
}

.ldio-5f9p1vioxma > div > div {
  animation: ldio-5f9p1vioxma 1s linear infinite;
  position: absolute
}

.ldio-5f9p1vioxma > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #954a4a;
  background:#d7ecf1
}

.ldio-5f9p1vioxma > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #954a4a;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-alu7sn2q8i9 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-5f9p1vioxma {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-5f9p1vioxma div { box-sizing: content-box; }
/* generated by https://loading.io/ */

#welcomebg{
  background: url('../assets/bg5.jpg') no-repeat center center/cover;
  filter:sepia(1);
}
#enter-button{
  margin:auto;
}

.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
</style>
<script>
import Loading from 'vue-loading-overlay'
import 'vue-loading-overlay/dist/vue-loading.css'
export default {
  data () {
    return {
      isLoading: true,
      fullPage: true,
      show: true
    }
  },
  components: {
    Loading
  },
  mounted () {
    this.isLoading = true
    // simulate AJAX
    setTimeout(() => {
      this.isLoading = false
    }, 3000)
  }
}
</script>
